/* A Bison parser, made by GNU Bison 3.0.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2013 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* All symbols defined below should begin with luaY_ or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output.  */
#define YYBISON 1

/* Bison version.  */
#define YYBISON_VERSION "3.0.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* Copy the first part of user declarations.  */
#line 1 "lua.y" /* yacc.c:339  */


char *rcs_luastx = "$Id: lua.stx,v 3.47 1997/06/19 17:46:12 roberto Exp $";

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "luadebug.h"
#include "luamem.h"
#include "lex.h"
#include "opcode.h"
#include "hash.h"
#include "inout.h"
#include "tree.h"
#include "table.h"
#include "lua.h"
#include "func.h"

/* to avoid warnings generated by yacc */
int luaY_parse (void);
#define malloc luaI_malloc
#define realloc luaI_realloc
#define free luaI_free

#ifndef LISTING
#define LISTING 0
#endif

#ifndef CODE_BLOCK
#define CODE_BLOCK 256
#endif
static int   maxcode;
static int   maxmain;
static int   maxcurr;
static Byte  *funcCode = NULL;
static Byte **initcode;
static Byte  *basepc;
static int   maincode;
static int   pc;


#define MAXVAR 32
static Long    varbuffer[MAXVAR];    /* variables in an assignment list;
				it's long to store negative Word values */
static int     nvarbuffer=0;	     /* number of variables at a list */

#define MAXLOCALS 32
static TaggedString *localvar[MAXLOCALS];  /* store local variable names */
static int     nlocalvar=0;	     /* number of local variables */

#define MAXFIELDS FIELDS_PER_FLUSH*2

int lua_debug = 0;

/* Internal functions */

static void luaY_error (char *s)
{
  luaI_syntaxerror(s);
}

static void check_space (int i)
{
  if (pc+i>maxcurr-1)  /* 1 byte free to code HALT of main code */
    maxcurr = growvector(&basepc, maxcurr, Byte, codeEM, MAX_INT);
}

static void code_byte (Byte c)
{
 check_space(1);
 basepc[pc++] = c;
}

static void code_word (Word n)
{
  check_space(sizeof(Word));
  memcpy(basepc+pc, &n, sizeof(Word));
  pc += sizeof(Word);
}

static void code_float (real n)
{
  check_space(sizeof(real));
  memcpy(basepc+pc, &n, sizeof(real));
  pc += sizeof(real);
}

static void code_code (TFunc *tf)
{
  check_space(sizeof(TFunc *));
  memcpy(basepc+pc, &tf, sizeof(TFunc *));
  pc += sizeof(TFunc *);
}

static void code_word_at (Byte *p, int n)
{
  Word w = n;
  if (w != n)
    luaY_error("block too big");
  memcpy(p, &w, sizeof(Word));
}

static void flush_record (int n)
{
  if (n == 0) return;
  code_byte(STOREMAP);
  code_byte(n);
}

static void flush_list (int m, int n)
{
  if (n == 0) return;
  if (m == 0)
    code_byte(STORELIST0); 
  else
  if (m < 255)
  {
    code_byte(STORELIST);
    code_byte(m);
  }
  else
   luaY_error ("list constructor too long");
  code_byte(n);
}

static void store_localvar (TaggedString *name, int n)
{
 if (nlocalvar+n < MAXLOCALS)
  localvar[nlocalvar+n] = name;
 else
  luaY_error ("too many local variables");
 if (lua_debug)
   luaI_registerlocalvar(name, lua_linenumber);
}

static void add_localvar (TaggedString *name)
{
  store_localvar(name, 0);
  nlocalvar++;
}

static void add_varbuffer (Long var)
{
 if (nvarbuffer < MAXVAR)
  varbuffer[nvarbuffer++] = var;
 else
  luaY_error ("variable buffer overflow");
}

static void code_string (Word w)
{
  code_byte(PUSHSTRING);
  code_word(w);
}

static void code_constant (TaggedString *s)
{
  code_string(luaI_findconstant(s));
}

static void code_number (float f)
{ 
  Word i;
  if (f >= 0 && f <= (float)MAX_WORD && (float)(i=(Word)f) == f) {
   /* f has an (short) integer value */
   if (i <= 2) code_byte(PUSH0 + i);
   else if (i <= 255)
   {
    code_byte(PUSHBYTE);
    code_byte(i);
   }
   else
   {
    code_byte(PUSHWORD);
    code_word(i);
   }
  }
  else
  {
   code_byte(PUSHFLOAT);
   code_float(f);
  }
}

/*
** Search a local name and if find return its index. If do not find return -1
*/
static int lua_localname (TaggedString *n)
{
 int i;
 for (i=nlocalvar-1; i >= 0; i--)
  if (n == localvar[i]) return i;	/* local var */
 return -1;		        /* global var */
}

/*
** Push a variable given a number. If number is positive, push global variable
** indexed by (number -1). If negative, push local indexed by ABS(number)-1.
** Otherwise, if zero, push indexed variable (record).
*/
static void lua_pushvar (Long number)
{ 
 if (number > 0)	/* global var */
 {
  code_byte(PUSHGLOBAL);
  code_word(number-1);
 }
 else if (number < 0)	/* local var */
 {
  number = (-number) - 1;
  if (number < 10) code_byte(PUSHLOCAL0 + number);
  else
  {
   code_byte(PUSHLOCAL);
   code_byte(number);
  }
 }
 else
 {
  code_byte(PUSHINDEXED);
 }
}

static void lua_codeadjust (int n)
{
 if (n+nlocalvar == 0)
   code_byte(ADJUST0);
 else
 {
   code_byte(ADJUST);
   code_byte(n+nlocalvar);
 }
}

static void change2main (void)
{
  /* (re)store main values */
  pc=maincode; basepc=*initcode; maxcurr=maxmain;
  nlocalvar=0;
}

static void savemain (void)
{
  /* save main values */
  maincode=pc; *initcode=basepc; maxmain=maxcurr;
}

static void init_func (void)
{
  if (funcCode == NULL)	/* first function */
  {
   funcCode = newvector(CODE_BLOCK, Byte);
   maxcode = CODE_BLOCK;
  }
  savemain();  /* save main values */
  /* set func values */
  pc=0; basepc=funcCode; maxcurr=maxcode; 
  nlocalvar = 0;
  luaI_codedebugline(lua_linenumber);
}

static void codereturn (void)
{
  if (nlocalvar == 0)
    code_byte(RETCODE0);
  else
  {
    code_byte(RETCODE);
    code_byte(nlocalvar);
  }
}

void luaI_codedebugline (int line)
{
  static int lastline = 0;
  if (lua_debug && line != lastline)
  {
    code_byte(SETLINE);
    code_word(line);
    lastline = line;
  }
}

static int adjust_functioncall (Long exp, int i)
{
  if (exp <= 0)
    return -exp; /* exp is -list length */
  else
  {
    int temp = basepc[exp];
    basepc[exp] = i;
    return temp+i;
  }
}

static void adjust_mult_assign (int vars, Long exps, int temps)
{
  if (exps > 0)
  { /* must correct function call */
    int diff = vars - basepc[exps];
    if (diff >= 0)
      adjust_functioncall(exps, diff);
    else
    {
      adjust_functioncall(exps, 0);
      lua_codeadjust(temps);
    }
  }
  else if (vars != -exps)
    lua_codeadjust(temps);
}

static int close_parlist (int dots)
{
  if (!dots)
    lua_codeadjust(0);
  else
  {
    code_byte(VARARGS);
    code_byte(nlocalvar);
    add_localvar(luaI_createfixedstring("arg"));
  }
  return lua_linenumber;
}

static void storesinglevar (Long v)
{
 if (v > 0)		/* global var */
 {
   code_byte(STOREGLOBAL);
   code_word(v-1);
 }
 else if (v < 0)      /* local var */
 {
   int number = (-v) - 1;
   if (number < 10) code_byte(STORELOCAL0 + number);
   else
   {
     code_byte(STORELOCAL);
     code_byte(number);
   }
 }
 else 
   code_byte(STOREINDEXED0);
}

static void lua_codestore (int i)
{
 if (varbuffer[i] != 0)  /* global or local var */
  storesinglevar(varbuffer[i]);
 else				  /* indexed var */
 {
  int j;
  int upper=0;     	/* number of indexed variables upper */
  int param;		/* number of itens until indexed expression */
  for (j=i+1; j <nvarbuffer; j++)
   if (varbuffer[j] == 0) upper++;
  param = upper*2 + i;
  if (param == 0)
   code_byte(STOREINDEXED0);
  else
  {
   code_byte(STOREINDEXED);
   code_byte(param);
  }
 }
}

static void codeIf (Long thenAdd, Long elseAdd)
{
  Long elseinit = elseAdd+sizeof(Word)+1;
  if (pc == elseinit)		/* no else */
  {
    pc -= sizeof(Word)+1;
    elseinit = pc;
  }
  else
  {
    basepc[elseAdd] = JMP;
    code_word_at(basepc+elseAdd+1, pc-elseinit);
  }
  basepc[thenAdd] = IFFJMP;
  code_word_at(basepc+thenAdd+1,elseinit-(thenAdd+sizeof(Word)+1));
}


/*
** Parse LUA code.
*/
void lua_parse (TFunc *tf)
{
 initcode = &(tf->code);
 *initcode = newvector(CODE_BLOCK, Byte);
 maincode = 0; 
 maxmain = CODE_BLOCK;
 change2main();
 if (luaY_parse ()) lua_error("parse error");
 savemain();
 (*initcode)[maincode++] = RETCODE0;
 tf->size = maincode;
#if LISTING
{ static void PrintCode (Byte *c, Byte *end);
 PrintCode(*initcode,*initcode+maincode); }
#endif
}



#line 476 "y.tab.c" /* yacc.c:339  */

# ifndef YY_NULLPTR
#  if defined __cplusplus && 201103L <= __cplusplus
#   define YY_NULLPTR nullptr
#  else
#   define YY_NULLPTR 0
#  endif
# endif

/* Enabling verbose error messages.  */
#ifdef YYERROR_VERBOSE
# undef YYERROR_VERBOSE
# define YYERROR_VERBOSE 1
#else
# define YYERROR_VERBOSE 0
#endif

/* In a future release of Bison, this section will be replaced
   by #include "y.tab.h".  */
#ifndef YY_YY_Y_TAB_H_INCLUDED
# define YY_YY_Y_TAB_H_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int luaY_debug;
#endif

/* Token type.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum luaY_tokentype
  {
    WRONGTOKEN = 258,
    NIL = 259,
    IF = 260,
    THEN = 261,
    ELSE = 262,
    ELSEIF = 263,
    WHILE = 264,
    DO = 265,
    REPEAT = 266,
    UNTIL = 267,
    END = 268,
    RETURN = 269,
    LOCAL = 270,
    FUNCTION = 271,
    DOTS = 272,
    NUMBER = 273,
    STRING = 274,
    NAME = 275,
    AND = 276,
    OR = 277,
    EQ = 278,
    NE = 279,
    LE = 280,
    GE = 281,
    CONC = 282,
    UNARY = 283,
    NOT = 284
  };
#endif
/* Tokens.  */
#define WRONGTOKEN 258
#define NIL 259
#define IF 260
#define THEN 261
#define ELSE 262
#define ELSEIF 263
#define WHILE 264
#define DO 265
#define REPEAT 266
#define UNTIL 267
#define END 268
#define RETURN 269
#define LOCAL 270
#define FUNCTION 271
#define DOTS 272
#define NUMBER 273
#define STRING 274
#define NAME 275
#define AND 276
#define OR 277
#define EQ 278
#define NE 279
#define LE 280
#define GE 281
#define CONC 282
#define UNARY 283
#define NOT 284

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
typedef union YYSTYPE YYSTYPE;
union YYSTYPE
{
#line 413 "lua.y" /* yacc.c:355  */

 int   vInt;
 float vFloat;
 char *pChar;
 Word  vWord;
 Long  vLong;
 TFunc *pFunc;
 TaggedString *pTStr;

#line 584 "y.tab.c" /* yacc.c:355  */
};
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE luaY_lval;

int luaY_parse (void);

#endif /* !YY_YY_Y_TAB_H_INCLUDED  */

/* Copy the second part of user declarations.  */

#line 599 "y.tab.c" /* yacc.c:358  */

#ifdef short
# undef short
#endif

#ifdef YYTYPE_UINT8
typedef YYTYPE_UINT8 luaY_type_uint8;
#else
typedef unsigned char luaY_type_uint8;
#endif

#ifdef YYTYPE_INT8
typedef YYTYPE_INT8 luaY_type_int8;
#else
typedef signed char luaY_type_int8;
#endif

#ifdef YYTYPE_UINT16
typedef YYTYPE_UINT16 luaY_type_uint16;
#else
typedef unsigned short int luaY_type_uint16;
#endif

#ifdef YYTYPE_INT16
typedef YYTYPE_INT16 luaY_type_int16;
#else
typedef short int luaY_type_int16;
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif ! defined YYSIZE_T
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned int
# endif
#endif

#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif

#ifndef YY_ATTRIBUTE
# if (defined __GNUC__                                               \
      && (2 < __GNUC__ || (__GNUC__ == 2 && 96 <= __GNUC_MINOR__)))  \
     || defined __SUNPRO_C && 0x5110 <= __SUNPRO_C
#  define YY_ATTRIBUTE(Spec) __attribute__(Spec)
# else
#  define YY_ATTRIBUTE(Spec) /* empty */
# endif
#endif

#ifndef YY_ATTRIBUTE_PURE
# define YY_ATTRIBUTE_PURE   YY_ATTRIBUTE ((__pure__))
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#endif

#if !defined _Noreturn \
     && (!defined __STDC_VERSION__ || __STDC_VERSION__ < 201112)
# if defined _MSC_VER && 1200 <= _MSC_VER
#  define _Noreturn __declspec (noreturn)
# else
#  define _Noreturn YY_ATTRIBUTE ((__noreturn__))
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YYUSE(E) ((void) (E))
#else
# define YYUSE(E) /* empty */
#endif

#if defined __GNUC__ && 407 <= __GNUC__ * 100 + __GNUC_MINOR__
/* Suppress an incorrect diagnostic about luaY_lval being uninitialized.  */
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN \
    _Pragma ("GCC diagnostic push") \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")\
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# define YY_IGNORE_MAYBE_UNINITIALIZED_END \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif


#if ! defined luaY_overflow || YYERROR_VERBOSE

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* ! defined luaY_overflow || YYERROR_VERBOSE */


#if (! defined luaY_overflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union luaY_alloc
{
  luaY_type_int16 luaY_ss_alloc;
  YYSTYPE luaY_vs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (sizeof (union luaY_alloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (sizeof (luaY_type_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYSIZE_T luaY_newbytes;                                            \
        YYCOPY (&luaY_ptr->Stack_alloc, Stack, luaY_size);                    \
        Stack = &luaY_ptr->Stack_alloc;                                    \
        luaY_newbytes = luaY_stacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        luaY_ptr += luaY_newbytes / sizeof (*luaY_ptr);                          \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, (Count) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYSIZE_T luaY_i;                         \
          for (luaY_i = 0; luaY_i < (Count); luaY_i++)   \
            (Dst)[luaY_i] = (Src)[luaY_i];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  3
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   347

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  48
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  47
/* YYNRULES -- Number of rules.  */
#define YYNRULES  102
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  180

/* YYTRANSLATE[YYX] -- Symbol number corresponding to YYX as returned
   by luaY_lex, with out-of-bounds checking.  */
#define YYUNDEFTOK  2
#define YYMAXUTOK   284

#define YYTRANSLATE(YYX)                                                \
  ((unsigned int) (YYX) <= YYMAXUTOK ? luaY_translate[YYX] : YYUNDEFTOK)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by luaY_lex, without out-of-bounds checking.  */
static const luaY_type_uint8 luaY_translate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
      38,    39,    32,    30,    44,    31,    47,    33,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,    37,    40,
      26,    41,    25,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,    45,     2,    46,    36,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    42,     2,    43,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      27,    28,    29,    34,    35
};

#if YYDEBUG
  /* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const luaY_type_uint16 luaY_rline[] =
{
       0,   459,   459,   461,   462,   463,   466,   474,   475,   484,
     504,   505,   508,   508,   510,   513,   513,   521,   521,   527,
     538,   539,   545,   546,   547,   551,   551,   565,   566,   574,
     581,   584,   585,   586,   587,   588,   589,   590,   591,   592,
     593,   594,   595,   596,   597,   598,   599,   600,   601,   606,
     607,   608,   609,   609,   615,   615,   624,   624,   634,   643,
     644,   652,   654,   657,   658,   661,   662,   662,   673,   674,
     677,   678,   686,   687,   691,   690,   694,   699,   700,   704,
     705,   708,   709,   712,   713,   720,   723,   724,   727,   728,
     731,   732,   740,   746,   753,   754,   758,   765,   775,   778,
     779,   786,   787
};
#endif

#if YYDEBUG || YYERROR_VERBOSE || 0
/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const luaY_tname[] =
{
  "$end", "error", "$undefined", "WRONGTOKEN", "NIL", "IF", "THEN",
  "ELSE", "ELSEIF", "WHILE", "DO", "REPEAT", "UNTIL", "END", "RETURN",
  "LOCAL", "FUNCTION", "DOTS", "NUMBER", "STRING", "NAME", "AND", "OR",
  "EQ", "NE", "'>'", "'<'", "LE", "GE", "CONC", "'+'", "'-'", "'*'", "'/'",
  "UNARY", "NOT", "'^'", "':'", "'('", "')'", "';'", "'='", "'{'", "'}'",
  "','", "'['", "']'", "'.'", "$accept", "chunk", "chunklist", "function",
  "funcname", "body", "statlist", "sc", "stat", "@1", "@2", "elsepart",
  "block", "@3", "ret", "PrepJump", "expr1", "expr", "$@4", "$@5", "table",
  "@6", "functioncall", "funcvalue", "funcParams", "exprlist", "exprlist1",
  "@7", "parlist", "parlist1", "par", "fieldlist", "$@8", "semicolonpart",
  "lastcomma", "ffieldlist", "ffieldlist1", "ffield", "ffieldkey",
  "lfieldlist", "lfieldlist1", "varlist1", "var", "singlevar", "varexp",
  "localdeclist", "decinit", YY_NULLPTR
};
#endif

# ifdef YYPRINT
/* YYTOKNUM[NUM] -- (External) token number corresponding to the
   (internal) symbol number NUM (which must be that of a token).  */
static const luaY_type_uint16 luaY_toknum[] =
{
       0,   256,   257,   258,   259,   260,   261,   262,   263,   264,
     265,   266,   267,   268,   269,   270,   271,   272,   273,   274,
     275,   276,   277,   278,   279,    62,    60,   280,   281,   282,
      43,    45,    42,    47,   283,   284,    94,    58,    40,    41,
      59,    61,   123,   125,    44,    91,    93,    46
};
# endif

#define YYPACT_NINF -99

#define luaY_pact_value_is_default(Yystate) \
  (!!((Yystate) == (-99)))

#define YYTABLE_NINF -99

#define luaY_table_value_is_error(Yytable_value) \
  0

  /* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
     STATE-NUM.  */
static const luaY_type_int16 luaY_pact[] =
{
     -99,    11,   313,   -99,    67,   -99,   -99,   126,    13,    20,
     -99,   -99,   -24,   -99,   -99,   -17,   -14,   -10,   -99,    -9,
     -99,   -99,   -99,    67,    67,    67,   148,   -99,   -99,     5,
     -99,   -99,    36,    67,   -99,   268,   284,   -24,    32,   -99,
      -2,    14,    41,    43,   -99,   -99,     6,   -99,   -99,    67,
      20,    62,    67,    69,    78,    78,    60,   -99,   -99,   -99,
      67,    67,    67,    67,    67,    67,    67,    67,    67,    67,
      67,    67,   105,   200,    91,   -99,   -99,   -99,    67,    95,
     -99,    34,   -99,   100,    82,    32,     8,    63,   -99,   216,
     -99,   -99,   -99,   -99,   -99,   156,   156,   156,   156,   156,
     156,   183,   -18,   -18,    78,    78,    78,    81,    67,   268,
      83,    88,   -99,    93,   -99,    94,   -99,    67,    86,    67,
      32,   -99,   -99,   -99,    98,    97,   -99,   -99,   -99,   -99,
     -99,    67,    67,   242,   -99,   -13,   -99,    67,    99,   126,
     -99,   -99,   268,   -24,   -99,   284,   -99,    34,    85,   311,
     311,   -99,   -99,   -99,   268,   -13,   -99,   268,   -99,   -99,
     -99,   129,   -99,   -99,    67,   135,   -99,    88,   136,   -99,
     -99,   176,   -99,   -99,   -99,   -99,   -99,   -99,    85,   -99
};

  /* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
     Performed when YYTABLE does not specify something else to do.  Zero
     means the default is an error.  */
static const luaY_type_uint8 luaY_defact[] =
{
       3,     0,    27,     1,    56,    15,    17,    63,     0,     0,
      97,     5,    12,     2,    20,    56,     0,    98,    94,    59,
      49,    47,    48,    56,    56,    56,     0,    30,    45,     0,
      50,    98,    46,    56,    25,     0,    65,    12,    64,    99,
     101,     0,    98,     0,    13,     4,    56,    62,    58,    56,
       0,     0,    56,     0,    44,    51,    30,    29,    29,    29,
      56,    56,    56,    56,    56,    56,    56,    56,    56,    56,
      56,    56,    88,     0,     0,    10,    28,    66,    56,     0,
      21,    68,     6,     0,     0,    19,    93,     0,    60,     0,
      96,    31,    25,    52,    54,    32,    35,    34,    33,    36,
      37,    43,    38,    39,    40,    41,    42,    97,    56,    90,
       0,    79,    83,     0,    74,    79,    29,    56,    27,    56,
     102,   100,    73,    72,     0,    69,    70,     8,    61,    95,
      29,    56,    56,     0,    57,    80,    76,    56,    77,    80,
      89,    25,    29,    12,    26,    67,    25,     0,    22,    53,
      55,    86,    87,    84,    85,    81,    75,    91,    29,    18,
      11,     0,    71,    25,    56,     0,    78,    79,     0,     9,
      23,     0,    14,    82,    16,    29,    25,    29,    22,    24
};

  /* YYPGOTO[NTERM-NUM].  */
static const luaY_type_int16 luaY_pgoto[] =
{
     -99,   -99,   -99,   -99,   -99,   -99,   -99,   -32,    33,   -99,
     -99,   -26,   -69,   -99,    35,   -46,    -4,    -3,   -99,   -99,
     140,   -99,     1,   -99,   -99,   110,   -43,   -99,   -99,   -99,
      12,   -99,   -99,   -99,   -98,   -99,     3,    27,   -99,   -99,
     -99,   -99,    -1,   -99,     0,   -99,   -99
};

  /* YYDEFGOTO[NTERM-NUM].  */
static const luaY_type_int16 luaY_defgoto[] =
{
      -1,     1,     2,    11,    41,    82,   118,    45,    12,    33,
      34,   165,    74,    75,    13,    92,    35,    27,   131,   132,
      28,    29,    30,    15,    48,    37,    38,   119,   124,   125,
     126,   110,   138,   156,   136,   166,   111,   112,   113,   114,
     115,    16,    31,    18,    32,    40,    80
};

  /* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
     positive, shift that token.  If negative, reduce the rule whose
     number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const luaY_type_int16 luaY_table[] =
{
      26,    17,    19,    14,    36,    76,    85,   152,    42,    43,
      20,     3,    93,    94,    69,    70,    44,   140,    71,    54,
      55,    46,    56,   130,    21,    22,    10,    49,    51,    73,
      50,   -92,   108,    39,   -92,   120,    52,    23,    53,    78,
      10,    24,    79,    36,    25,   -63,    36,    72,    89,    86,
      87,   122,    81,   -98,   123,   -98,    95,    96,    97,    98,
      99,   100,   101,   102,   103,   104,   105,   106,   109,   173,
     141,    20,   158,    51,   -59,    36,    77,   161,   -59,    -7,
      83,    52,    88,    53,   148,    21,    22,    10,    52,    90,
      53,     4,   163,   164,   170,     5,   159,     6,    23,    91,
       7,     8,    24,   117,   133,    25,    10,   177,    52,    20,
      53,   160,   168,   142,    71,   121,   145,    17,    19,    14,
     127,   128,   -87,    21,    22,   107,   134,   149,   150,   176,
      20,   178,   135,   154,   137,   157,    23,   146,   139,   155,
      24,   147,   169,    25,    21,    22,    10,   -56,   172,   174,
     108,   143,   179,   144,    57,    47,    84,    23,   167,   162,
     171,    24,   153,     0,    25,     0,     0,     0,   -56,    58,
      59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
      69,    70,   175,     0,    71,    66,    67,    68,    69,    70,
       0,     0,    71,     0,     0,     0,     0,    58,    59,    60,
      61,    62,    63,    64,    65,    66,    67,    68,    69,    70,
     116,     0,    71,    67,    68,    69,    70,     0,     0,    71,
       0,    58,    59,    60,    61,    62,    63,    64,    65,    66,
      67,    68,    69,    70,     0,     0,    71,    58,    59,    60,
      61,    62,    63,    64,    65,    66,    67,    68,    69,    70,
       0,     0,    71,     0,     0,     0,     0,     0,     0,     0,
       0,     0,   129,    58,    59,    60,    61,    62,    63,    64,
      65,    66,    67,    68,    69,    70,     0,     0,    71,     0,
       0,     0,     0,     0,     0,     0,     0,     0,   151,    58,
      59,    60,    61,    62,    63,    64,    65,    66,    67,    68,
      69,    70,     0,     0,    71,   -30,   -30,   -30,   -30,   -30,
     -30,   -30,   -30,   -30,   -30,   -30,   -30,   -30,     4,     0,
     -30,     0,     5,     0,     6,     0,     0,     7,     8,     9,
       0,     0,     0,    10,    60,    61,    62,    63,    64,    65,
      66,    67,    68,    69,    70,     0,     0,    71
};

static const luaY_type_int16 luaY_check[] =
{
       4,     2,     2,     2,     7,    37,    49,    20,     9,     9,
       4,     0,    58,    59,    32,    33,    40,   115,    36,    23,
      24,    38,    25,    92,    18,    19,    20,    41,    37,    33,
      44,    41,    45,    20,    44,    78,    45,    31,    47,    41,
      20,    35,    44,    46,    38,    39,    49,    42,    52,    50,
      50,    17,    38,    45,    20,    47,    60,    61,    62,    63,
      64,    65,    66,    67,    68,    69,    70,    71,    72,   167,
     116,     4,   141,    37,    38,    78,    44,   146,    42,    38,
      37,    45,    20,    47,   130,    18,    19,    20,    45,    20,
      47,     5,     7,     8,   163,     9,   142,    11,    31,    39,
      14,    15,    35,    12,   108,    38,    20,   176,    45,     4,
      47,   143,   158,   117,    36,    20,   119,   118,   118,   118,
      20,    39,    41,    18,    19,    20,    43,   131,   132,   175,
       4,   177,    44,   137,    41,   139,    31,    39,    44,    40,
      35,    44,    13,    38,    18,    19,    20,    42,    13,    13,
      45,   118,   178,   118,     6,    15,    46,    31,   155,   147,
     164,    35,   135,    -1,    38,    -1,    -1,    -1,    42,    21,
      22,    23,    24,    25,    26,    27,    28,    29,    30,    31,
      32,    33,     6,    -1,    36,    29,    30,    31,    32,    33,
      -1,    -1,    36,    -1,    -1,    -1,    -1,    21,    22,    23,
      24,    25,    26,    27,    28,    29,    30,    31,    32,    33,
      10,    -1,    36,    30,    31,    32,    33,    -1,    -1,    36,
      -1,    21,    22,    23,    24,    25,    26,    27,    28,    29,
      30,    31,    32,    33,    -1,    -1,    36,    21,    22,    23,
      24,    25,    26,    27,    28,    29,    30,    31,    32,    33,
      -1,    -1,    36,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    -1,    46,    21,    22,    23,    24,    25,    26,    27,
      28,    29,    30,    31,    32,    33,    -1,    -1,    36,    -1,
      -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    46,    21,
      22,    23,    24,    25,    26,    27,    28,    29,    30,    31,
      32,    33,    -1,    -1,    36,    21,    22,    23,    24,    25,
      26,    27,    28,    29,    30,    31,    32,    33,     5,    -1,
      36,    -1,     9,    -1,    11,    -1,    -1,    14,    15,    16,
      -1,    -1,    -1,    20,    23,    24,    25,    26,    27,    28,
      29,    30,    31,    32,    33,    -1,    -1,    36
};

  /* YYSTOS[STATE-NUM] -- The (internal number of the) accessing
     symbol of state STATE-NUM.  */
static const luaY_type_uint8 luaY_stos[] =
{
       0,    49,    50,     0,     5,     9,    11,    14,    15,    16,
      20,    51,    56,    62,    70,    71,    89,    90,    91,    92,
       4,    18,    19,    31,    35,    38,    64,    65,    68,    69,
      70,    90,    92,    57,    58,    64,    65,    73,    74,    20,
      93,    52,    90,    92,    40,    55,    38,    68,    72,    41,
      44,    37,    45,    47,    64,    64,    65,     6,    21,    22,
      23,    24,    25,    26,    27,    28,    29,    30,    31,    32,
      33,    36,    42,    64,    60,    61,    55,    44,    41,    44,
      94,    38,    53,    37,    73,    74,    90,    92,    20,    64,
      20,    39,    63,    63,    63,    64,    64,    64,    64,    64,
      64,    64,    64,    64,    64,    64,    64,    20,    45,    64,
      79,    84,    85,    86,    87,    88,    10,    12,    54,    75,
      74,    20,    17,    20,    76,    77,    78,    20,    39,    46,
      60,    66,    67,    64,    43,    44,    82,    41,    80,    44,
      82,    63,    64,    56,    62,    65,    39,    44,    63,    64,
      64,    46,    20,    85,    64,    40,    81,    64,    60,    63,
      55,    60,    78,     7,     8,    59,    83,    84,    63,    13,
      60,    64,    13,    82,    13,     6,    63,    60,    63,    59
};

  /* YYR1[YYN] -- Symbol number of symbol that rule YYN derives.  */
static const luaY_type_uint8 luaY_r1[] =
{
       0,    48,    49,    50,    50,    50,    51,    52,    52,    53,
      54,    54,    55,    55,    56,    57,    56,    58,    56,    56,
      56,    56,    59,    59,    59,    61,    60,    62,    62,    63,
      64,    65,    65,    65,    65,    65,    65,    65,    65,    65,
      65,    65,    65,    65,    65,    65,    65,    65,    65,    65,
      65,    65,    66,    65,    67,    65,    69,    68,    70,    71,
      71,    72,    72,    73,    73,    74,    75,    74,    76,    76,
      77,    77,    78,    78,    80,    79,    79,    81,    81,    82,
      82,    83,    83,    84,    84,    85,    86,    86,    87,    87,
      88,    88,    89,    89,    90,    90,    90,    91,    92,    93,
      93,    94,    94
};

  /* YYR2[YYN] -- Number of symbols on the right hand side of rule YYN.  */
static const luaY_type_uint8 luaY_r2[] =
{
       0,     2,     2,     0,     3,     2,     3,     1,     3,     5,
       0,     3,     0,     1,     8,     0,     8,     0,     6,     3,
       1,     3,     0,     2,     7,     0,     3,     0,     3,     0,
       1,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3,     3,     2,     1,     1,     1,     1,     1,
       1,     2,     0,     5,     0,     5,     0,     4,     2,     1,
       3,     3,     1,     0,     1,     1,     0,     4,     0,     1,
       1,     3,     1,     1,     0,     3,     2,     0,     2,     0,
       1,     0,     2,     1,     3,     3,     3,     1,     0,     2,
       1,     3,     1,     3,     1,     4,     3,     1,     1,     1,
       3,     0,     2
};


#define luaY_errok         (luaY_errstatus = 0)
#define luaY_clearin       (luaY_char = YYEMPTY)
#define YYEMPTY         (-2)
#define YYEOF           0

#define YYACCEPT        goto luaY_acceptlab
#define YYABORT         goto luaY_abortlab
#define YYERROR         goto luaY_errorlab


#define YYRECOVERING()  (!!luaY_errstatus)

#define YYBACKUP(Token, Value)                                  \
do                                                              \
  if (luaY_char == YYEMPTY)                                        \
    {                                                           \
      luaY_char = (Token);                                         \
      luaY_lval = (Value);                                         \
      YYPOPSTACK (luaY_len);                                       \
      luaY_state = *luaY_ssp;                                         \
      goto luaY_backup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      luaY_error (YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (0)

/* Error token number */
#define YYTERROR        1
#define YYERRCODE       256



/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (luaY_debug)                                  \
    YYFPRINTF Args;                             \
} while (0)

/* This macro is provided for backward compatibility. */
#ifndef YY_LOCATION_PRINT
# define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#endif


# define YY_SYMBOL_PRINT(Title, Type, Value, Location)                    \
do {                                                                      \
  if (luaY_debug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      luaY__symbol_print (stderr,                                            \
                  Type, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*----------------------------------------.
| Print this symbol's value on YYOUTPUT.  |
`----------------------------------------*/

static void
luaY__symbol_value_print (FILE *luaY_output, int luaY_type, YYSTYPE const * const luaY_valuep)
{
  FILE *luaY_o = luaY_output;
  YYUSE (luaY_o);
  if (!luaY_valuep)
    return;
# ifdef YYPRINT
  if (luaY_type < YYNTOKENS)
    YYPRINT (luaY_output, luaY_toknum[luaY_type], *luaY_valuep);
# endif
  YYUSE (luaY_type);
}


/*--------------------------------.
| Print this symbol on YYOUTPUT.  |
`--------------------------------*/

static void
luaY__symbol_print (FILE *luaY_output, int luaY_type, YYSTYPE const * const luaY_valuep)
{
  YYFPRINTF (luaY_output, "%s %s (",
             luaY_type < YYNTOKENS ? "token" : "nterm", luaY_tname[luaY_type]);

  luaY__symbol_value_print (luaY_output, luaY_type, luaY_valuep);
  YYFPRINTF (luaY_output, ")");
}

/*------------------------------------------------------------------.
| luaY__stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
luaY__stack_print (luaY_type_int16 *luaY_bottom, luaY_type_int16 *luaY_top)
{
  YYFPRINTF (stderr, "Stack now");
  for (; luaY_bottom <= luaY_top; luaY_bottom++)
    {
      int luaY_bot = *luaY_bottom;
      YYFPRINTF (stderr, " %d", luaY_bot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (luaY_debug)                                                  \
    luaY__stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
luaY__reduce_print (luaY_type_int16 *luaY_ssp, YYSTYPE *luaY_vsp, int luaY_rule)
{
  unsigned long int luaY_lno = luaY_rline[luaY_rule];
  int luaY_nrhs = luaY_r2[luaY_rule];
  int luaY_i;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %lu):\n",
             luaY_rule - 1, luaY_lno);
  /* The symbols being reduced.  */
  for (luaY_i = 0; luaY_i < luaY_nrhs; luaY_i++)
    {
      YYFPRINTF (stderr, "   $%d = ", luaY_i + 1);
      luaY__symbol_print (stderr,
                       luaY_stos[luaY_ssp[luaY_i + 1 - luaY_nrhs]],
                       &(luaY_vsp[(luaY_i + 1) - (luaY_nrhs)])
                                              );
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (luaY_debug)                          \
    luaY__reduce_print (luaY_ssp, luaY_vsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int luaY_debug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args)
# define YY_SYMBOL_PRINT(Title, Type, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif


#if YYERROR_VERBOSE

# ifndef luaY_strlen
#  if defined __GLIBC__ && defined _STRING_H
#   define luaY_strlen strlen
#  else
/* Return the length of YYSTR.  */
static YYSIZE_T
luaY_strlen (const char *luaY_str)
{
  YYSIZE_T luaY_len;
  for (luaY_len = 0; luaY_str[luaY_len]; luaY_len++)
    continue;
  return luaY_len;
}
#  endif
# endif

# ifndef luaY_stpcpy
#  if defined __GLIBC__ && defined _STRING_H && defined _GNU_SOURCE
#   define luaY_stpcpy stpcpy
#  else
/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
   YYDEST.  */
static char *
luaY_stpcpy (char *luaY_dest, const char *luaY_src)
{
  char *luaY_d = luaY_dest;
  const char *luaY_s = luaY_src;

  while ((*luaY_d++ = *luaY_s++) != '\0')
    continue;

  return luaY_d - 1;
}
#  endif
# endif

# ifndef luaY_tnamerr
/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
   quotes and backslashes, so that it's suitable for luaY_error.  The
   heuristic is that double-quoting is unnecessary unless the string
   contains an apostrophe, a comma, or backslash (other than
   backslash-backslash).  YYSTR is taken from luaY_tname.  If YYRES is
   null, do not copy; instead, return the length of what the result
   would have been.  */
static YYSIZE_T
luaY_tnamerr (char *luaY_res, const char *luaY_str)
{
  if (*luaY_str == '"')
    {
      YYSIZE_T luaY_n = 0;
      char const *luaY_p = luaY_str;

      for (;;)
        switch (*++luaY_p)
          {
          case '\'':
          case ',':
            goto do_not_strip_quotes;

          case '\\':
            if (*++luaY_p != '\\')
              goto do_not_strip_quotes;
            /* Fall through.  */
          default:
            if (luaY_res)
              luaY_res[luaY_n] = *luaY_p;
            luaY_n++;
            break;

          case '"':
            if (luaY_res)
              luaY_res[luaY_n] = '\0';
            return luaY_n;
          }
    do_not_strip_quotes: ;
    }

  if (! luaY_res)
    return luaY_strlen (luaY_str);

  return luaY_stpcpy (luaY_res, luaY_str) - luaY_res;
}
# endif

/* Copy into *YYMSG, which is of size *YYMSG_ALLOC, an error message
   about the unexpected token YYTOKEN for the state stack whose top is
   YYSSP.

   Return 0 if *YYMSG was successfully written.  Return 1 if *YYMSG is
   not large enough to hold the message.  In that case, also set
   *YYMSG_ALLOC to the required number of bytes.  Return 2 if the
   required number of bytes is too large to store.  */
static int
luaY_syntax_error (YYSIZE_T *luaY_msg_alloc, char **luaY_msg,
                luaY_type_int16 *luaY_ssp, int luaY_token)
{
  YYSIZE_T luaY_size0 = luaY_tnamerr (YY_NULLPTR, luaY_tname[luaY_token]);
  YYSIZE_T luaY_size = luaY_size0;
  enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
  /* Internationalized format string. */
  const char *luaY_format = YY_NULLPTR;
  /* Arguments of luaY_format. */
  char const *luaY_arg[YYERROR_VERBOSE_ARGS_MAXIMUM];
  /* Number of reported tokens (one for the "unexpected", one per
     "expected"). */
  int luaY_count = 0;

  /* There are many possibilities here to consider:
     - If this state is a consistent state with a default action, then
       the only way this function was invoked is if the default action
       is an error action.  In that case, don't check for expected
       tokens because there are none.
     - The only way there can be no lookahead present (in luaY_char) is if
       this state is a consistent state with a default action.  Thus,
       detecting the absence of a lookahead is sufficient to determine
       that there is no unexpected or expected token to report.  In that
       case, just report a simple "syntax error".
     - Don't assume there isn't a lookahead just because this state is a
       consistent state with a default action.  There might have been a
       previous inconsistent state, consistent state with a non-default
       action, or user semantic action that manipulated luaY_char.
     - Of course, the expected token list depends on states to have
       correct lookahead information, and it depends on the parser not
       to perform extra reductions after fetching a lookahead from the
       scanner and before detecting a syntax error.  Thus, state merging
       (from LALR or IELR) and default reductions corrupt the expected
       token list.  However, the list is correct for canonical LR with
       one exception: it will still contain any token that will not be
       accepted due to an error action in a later state.
  */
  if (luaY_token != YYEMPTY)
    {
      int luaY_n = luaY_pact[*luaY_ssp];
      luaY_arg[luaY_count++] = luaY_tname[luaY_token];
      if (!luaY_pact_value_is_default (luaY_n))
        {
          /* Start YYX at -YYN if negative to avoid negative indexes in
             YYCHECK.  In other words, skip the first -YYN actions for
             this state because they are default actions.  */
          int luaY_xbegin = luaY_n < 0 ? -luaY_n : 0;
          /* Stay within bounds of both luaY_check and luaY_tname.  */
          int luaY_checklim = YYLAST - luaY_n + 1;
          int luaY_xend = luaY_checklim < YYNTOKENS ? luaY_checklim : YYNTOKENS;
          int luaY_x;

          for (luaY_x = luaY_xbegin; luaY_x < luaY_xend; ++luaY_x)
            if (luaY_check[luaY_x + luaY_n] == luaY_x && luaY_x != YYTERROR
                && !luaY_table_value_is_error (luaY_table[luaY_x + luaY_n]))
              {
                if (luaY_count == YYERROR_VERBOSE_ARGS_MAXIMUM)
                  {
                    luaY_count = 1;
                    luaY_size = luaY_size0;
                    break;
                  }
                luaY_arg[luaY_count++] = luaY_tname[luaY_x];
                {
                  YYSIZE_T luaY_size1 = luaY_size + luaY_tnamerr (YY_NULLPTR, luaY_tname[luaY_x]);
                  if (! (luaY_size <= luaY_size1
                         && luaY_size1 <= YYSTACK_ALLOC_MAXIMUM))
                    return 2;
                  luaY_size = luaY_size1;
                }
              }
        }
    }

  switch (luaY_count)
    {
# define YYCASE_(N, S)                      \
      case N:                               \
        luaY_format = S;                       \
      break
      YYCASE_(0, YY_("syntax error"));
      YYCASE_(1, YY_("syntax error, unexpected %s"));
      YYCASE_(2, YY_("syntax error, unexpected %s, expecting %s"));
      YYCASE_(3, YY_("syntax error, unexpected %s, expecting %s or %s"));
      YYCASE_(4, YY_("syntax error, unexpected %s, expecting %s or %s or %s"));
      YYCASE_(5, YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s"));
# undef YYCASE_
    }

  {
    YYSIZE_T luaY_size1 = luaY_size + luaY_strlen (luaY_format);
    if (! (luaY_size <= luaY_size1 && luaY_size1 <= YYSTACK_ALLOC_MAXIMUM))
      return 2;
    luaY_size = luaY_size1;
  }

  if (*luaY_msg_alloc < luaY_size)
    {
      *luaY_msg_alloc = 2 * luaY_size;
      if (! (luaY_size <= *luaY_msg_alloc
             && *luaY_msg_alloc <= YYSTACK_ALLOC_MAXIMUM))
        *luaY_msg_alloc = YYSTACK_ALLOC_MAXIMUM;
      return 1;
    }

  /* Avoid sprintf, as that infringes on the user's name space.
     Don't have undefined behavior even if the translation
     produced a string with the wrong number of "%s"s.  */
  {
    char *luaY_p = *luaY_msg;
    int luaY_i = 0;
    while ((*luaY_p = *luaY_format) != '\0')
      if (*luaY_p == '%' && luaY_format[1] == 's' && luaY_i < luaY_count)
        {
          luaY_p += luaY_tnamerr (luaY_p, luaY_arg[luaY_i++]);
          luaY_format += 2;
        }
      else
        {
          luaY_p++;
          luaY_format++;
        }
  }
  return 0;
}
#endif /* YYERROR_VERBOSE */

/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
luaY_destruct (const char *luaY_msg, int luaY_type, YYSTYPE *luaY_valuep)
{
  YYUSE (luaY_valuep);
  if (!luaY_msg)
    luaY_msg = "Deleting";
  YY_SYMBOL_PRINT (luaY_msg, luaY_type, luaY_valuep, luaY_locationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YYUSE (luaY_type);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}




/* The lookahead symbol.  */
int luaY_char;

/* The semantic value of the lookahead symbol.  */
YYSTYPE luaY_lval;
/* Number of syntax errors so far.  */
int luaY_nerrs;


/*----------.
| luaY_parse.  |
`----------*/

int
luaY_parse (void)
{
    int luaY_state;
    /* Number of tokens to shift before error messages enabled.  */
    int luaY_errstatus;

    /* The stacks and their tools:
       'luaY_ss': related to states.
       'luaY_vs': related to semantic values.

       Refer to the stacks through separate pointers, to allow luaY_overflow
       to reallocate them elsewhere.  */

    /* The state stack.  */
    luaY_type_int16 luaY_ssa[YYINITDEPTH];
    luaY_type_int16 *luaY_ss;
    luaY_type_int16 *luaY_ssp;

    /* The semantic value stack.  */
    YYSTYPE luaY_vsa[YYINITDEPTH];
    YYSTYPE *luaY_vs;
    YYSTYPE *luaY_vsp;

    YYSIZE_T luaY_stacksize;

  int luaY_n;
  int luaY_result;
  /* Lookahead token as an internal (translated) token number.  */
  int luaY_token = 0;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE luaY_val;

#if YYERROR_VERBOSE
  /* Buffer for error messages, and its allocated size.  */
  char luaY_msgbuf[128];
  char *luaY_msg = luaY_msgbuf;
  YYSIZE_T luaY_msg_alloc = sizeof luaY_msgbuf;
#endif

#define YYPOPSTACK(N)   (luaY_vsp -= (N), luaY_ssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int luaY_len = 0;

  luaY_ssp = luaY_ss = luaY_ssa;
  luaY_vsp = luaY_vs = luaY_vsa;
  luaY_stacksize = YYINITDEPTH;

  YYDPRINTF ((stderr, "Starting parse\n"));

  luaY_state = 0;
  luaY_errstatus = 0;
  luaY_nerrs = 0;
  luaY_char = YYEMPTY; /* Cause a token to be read.  */
  goto luaY_setstate;

/*------------------------------------------------------------.
| luaY_newstate -- Push a new state, which is found in luaY_state.  |
`------------------------------------------------------------*/
 luaY_newstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  luaY_ssp++;

 luaY_setstate:
  *luaY_ssp = luaY_state;

  if (luaY_ss + luaY_stacksize - 1 <= luaY_ssp)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T luaY_size = luaY_ssp - luaY_ss + 1;

#ifdef luaY_overflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        YYSTYPE *luaY_vs1 = luaY_vs;
        luaY_type_int16 *luaY_ss1 = luaY_ss;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if luaY_overflow is a macro.  */
        luaY_overflow (YY_("memory exhausted"),
                    &luaY_ss1, luaY_size * sizeof (*luaY_ssp),
                    &luaY_vs1, luaY_size * sizeof (*luaY_vsp),
                    &luaY_stacksize);

        luaY_ss = luaY_ss1;
        luaY_vs = luaY_vs1;
      }
#else /* no luaY_overflow */
# ifndef YYSTACK_RELOCATE
      goto luaY_exhaustedlab;
# else
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= luaY_stacksize)
        goto luaY_exhaustedlab;
      luaY_stacksize *= 2;
      if (YYMAXDEPTH < luaY_stacksize)
        luaY_stacksize = YYMAXDEPTH;

      {
        luaY_type_int16 *luaY_ss1 = luaY_ss;
        union luaY_alloc *luaY_ptr =
          (union luaY_alloc *) YYSTACK_ALLOC (YYSTACK_BYTES (luaY_stacksize));
        if (! luaY_ptr)
          goto luaY_exhaustedlab;
        YYSTACK_RELOCATE (luaY_ss_alloc, luaY_ss);
        YYSTACK_RELOCATE (luaY_vs_alloc, luaY_vs);
#  undef YYSTACK_RELOCATE
        if (luaY_ss1 != luaY_ssa)
          YYSTACK_FREE (luaY_ss1);
      }
# endif
#endif /* no luaY_overflow */

      luaY_ssp = luaY_ss + luaY_size - 1;
      luaY_vsp = luaY_vs + luaY_size - 1;

      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                  (unsigned long int) luaY_stacksize));

      if (luaY_ss + luaY_stacksize - 1 <= luaY_ssp)
        YYABORT;
    }

  YYDPRINTF ((stderr, "Entering state %d\n", luaY_state));

  if (luaY_state == YYFINAL)
    YYACCEPT;

  goto luaY_backup;

/*-----------.
| luaY_backup.  |
`-----------*/
luaY_backup:

  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  luaY_n = luaY_pact[luaY_state];
  if (luaY_pact_value_is_default (luaY_n))
    goto luaY_default;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
  if (luaY_char == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      luaY_char = luaY_lex ();
    }

  if (luaY_char <= YYEOF)
    {
      luaY_char = luaY_token = YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      luaY_token = YYTRANSLATE (luaY_char);
      YY_SYMBOL_PRINT ("Next token is", luaY_token, &luaY_lval, &luaY_lloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  luaY_n += luaY_token;
  if (luaY_n < 0 || YYLAST < luaY_n || luaY_check[luaY_n] != luaY_token)
    goto luaY_default;
  luaY_n = luaY_table[luaY_n];
  if (luaY_n <= 0)
    {
      if (luaY_table_value_is_error (luaY_n))
        goto luaY_errlab;
      luaY_n = -luaY_n;
      goto luaY_reduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (luaY_errstatus)
    luaY_errstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", luaY_token, &luaY_lval, &luaY_lloc);

  /* Discard the shifted token.  */
  luaY_char = YYEMPTY;

  luaY_state = luaY_n;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++luaY_vsp = luaY_lval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  goto luaY_newstate;


/*-----------------------------------------------------------.
| luaY_default -- do the default action for the current state.  |
`-----------------------------------------------------------*/
luaY_default:
  luaY_n = luaY_defact[luaY_state];
  if (luaY_n == 0)
    goto luaY_errlab;
  goto luaY_reduce;


/*-----------------------------.
| luaY_reduce -- Do a reduction.  |
`-----------------------------*/
luaY_reduce:
  /* luaY_n is the number of a rule to reduce with.  */
  luaY_len = luaY_r2[luaY_n];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  luaY_val = luaY_vsp[1-luaY_len];


  YY_REDUCE_PRINT (luaY_n);
  switch (luaY_n)
    {
        case 6:
#line 467 "lua.y" /* yacc.c:1646  */
    { 
		code_byte(PUSHFUNCTION);
		code_code((luaY_vsp[0].pFunc));
		storesinglevar((luaY_vsp[-1].vLong));
	       }
#line 1843 "y.tab.c" /* yacc.c:1646  */
    break;

  case 7:
#line 474 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vLong) =(luaY_vsp[0].vLong); init_func(); }
#line 1849 "y.tab.c" /* yacc.c:1646  */
    break;

  case 8:
#line 476 "lua.y" /* yacc.c:1646  */
    {
	  code_constant((luaY_vsp[0].pTStr));
	  (luaY_val.vLong) = 0;  /* indexed variable */
	  init_func();
	  add_localvar(luaI_createfixedstring("self"));
	}
#line 1860 "y.tab.c" /* yacc.c:1646  */
    break;

  case 9:
#line 485 "lua.y" /* yacc.c:1646  */
    {
          codereturn();
	  (luaY_val.pFunc) = new(TFunc);
          luaI_initTFunc((luaY_val.pFunc));
	  (luaY_val.pFunc)->size = pc;
	  (luaY_val.pFunc)->code = newvector(pc, Byte);
	  (luaY_val.pFunc)->lineDefined = (luaY_vsp[-3].vInt);
	  memcpy((luaY_val.pFunc)->code, basepc, pc*sizeof(Byte));
          if (lua_debug)
            luaI_closelocalvars((luaY_val.pFunc));
	  /* save func values */
	  funcCode = basepc; maxcode=maxcurr;
#if LISTING
                PrintCode(funcCode,funcCode+pc);
#endif
	  change2main();  /* change back to main code */
	}
#line 1882 "y.tab.c" /* yacc.c:1646  */
    break;

  case 14:
#line 511 "lua.y" /* yacc.c:1646  */
    { codeIf((luaY_vsp[-4].vLong), (luaY_vsp[-2].vLong)); }
#line 1888 "y.tab.c" /* yacc.c:1646  */
    break;

  case 15:
#line 513 "lua.y" /* yacc.c:1646  */
    {(luaY_val.vLong)=pc;}
#line 1894 "y.tab.c" /* yacc.c:1646  */
    break;

  case 16:
#line 514 "lua.y" /* yacc.c:1646  */
    {
        basepc[(luaY_vsp[-3].vLong)] = IFFJMP;
	code_word_at(basepc+(luaY_vsp[-3].vLong)+1, pc - ((luaY_vsp[-3].vLong) + sizeof(Word)+1));
        basepc[(luaY_vsp[-1].vLong)] = UPJMP;
	code_word_at(basepc+(luaY_vsp[-1].vLong)+1, pc - ((luaY_vsp[-6].vLong)));
       }
#line 1905 "y.tab.c" /* yacc.c:1646  */
    break;

  case 17:
#line 521 "lua.y" /* yacc.c:1646  */
    {(luaY_val.vLong)=pc;}
#line 1911 "y.tab.c" /* yacc.c:1646  */
    break;

  case 18:
#line 522 "lua.y" /* yacc.c:1646  */
    {
        basepc[(luaY_vsp[0].vLong)] = IFFUPJMP;
	code_word_at(basepc+(luaY_vsp[0].vLong)+1, pc - ((luaY_vsp[-4].vLong)));
       }
#line 1920 "y.tab.c" /* yacc.c:1646  */
    break;

  case 19:
#line 528 "lua.y" /* yacc.c:1646  */
    {
        {
         int i;
         adjust_mult_assign(nvarbuffer, (luaY_vsp[0].vLong), (luaY_vsp[-2].vInt) * 2 + nvarbuffer);
	 for (i=nvarbuffer-1; i>=0; i--)
	  lua_codestore (i);
	 if ((luaY_vsp[-2].vInt) > 1 || ((luaY_vsp[-2].vInt) == 1 && varbuffer[0] != 0))
	  lua_codeadjust (0);
	}
       }
#line 1935 "y.tab.c" /* yacc.c:1646  */
    break;

  case 20:
#line 538 "lua.y" /* yacc.c:1646  */
    {;}
#line 1941 "y.tab.c" /* yacc.c:1646  */
    break;

  case 21:
#line 540 "lua.y" /* yacc.c:1646  */
    { nlocalvar += (luaY_vsp[-1].vInt);
	  adjust_mult_assign((luaY_vsp[-1].vInt), (luaY_vsp[0].vInt), 0);
	}
#line 1949 "y.tab.c" /* yacc.c:1646  */
    break;

  case 24:
#line 548 "lua.y" /* yacc.c:1646  */
    { codeIf((luaY_vsp[-3].vLong), (luaY_vsp[-1].vLong)); }
#line 1955 "y.tab.c" /* yacc.c:1646  */
    break;

  case 25:
#line 551 "lua.y" /* yacc.c:1646  */
    {(luaY_val.vInt) = nlocalvar;}
#line 1961 "y.tab.c" /* yacc.c:1646  */
    break;

  case 26:
#line 552 "lua.y" /* yacc.c:1646  */
    {
	  if (nlocalvar != (luaY_vsp[-2].vInt))
	  {
           if (lua_debug)
             for (; nlocalvar > (luaY_vsp[-2].vInt); nlocalvar--)
               luaI_unregisterlocalvar(lua_linenumber);
           else
             nlocalvar = (luaY_vsp[-2].vInt);
	   lua_codeadjust (0);
	  }
         }
#line 1977 "y.tab.c" /* yacc.c:1646  */
    break;

  case 28:
#line 567 "lua.y" /* yacc.c:1646  */
    {
	   adjust_functioncall((luaY_vsp[-1].vLong), MULT_RET);
           codereturn();
          }
#line 1986 "y.tab.c" /* yacc.c:1646  */
    break;

  case 29:
#line 574 "lua.y" /* yacc.c:1646  */
    { 
	  (luaY_val.vLong) = pc;
	  code_byte(0);		/* open space */
	  code_word (0);
         }
#line 1996 "y.tab.c" /* yacc.c:1646  */
    break;

  case 30:
#line 581 "lua.y" /* yacc.c:1646  */
    { adjust_functioncall((luaY_vsp[0].vLong), 1); }
#line 2002 "y.tab.c" /* yacc.c:1646  */
    break;

  case 31:
#line 584 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vLong) = (luaY_vsp[-1].vLong); }
#line 2008 "y.tab.c" /* yacc.c:1646  */
    break;

  case 32:
#line 585 "lua.y" /* yacc.c:1646  */
    { code_byte(EQOP);   (luaY_val.vLong) = 0; }
#line 2014 "y.tab.c" /* yacc.c:1646  */
    break;

  case 33:
#line 586 "lua.y" /* yacc.c:1646  */
    { code_byte(LTOP);   (luaY_val.vLong) = 0; }
#line 2020 "y.tab.c" /* yacc.c:1646  */
    break;

  case 34:
#line 587 "lua.y" /* yacc.c:1646  */
    { code_byte(GTOP);   (luaY_val.vLong) = 0; }
#line 2026 "y.tab.c" /* yacc.c:1646  */
    break;

  case 35:
#line 588 "lua.y" /* yacc.c:1646  */
    { code_byte(EQOP); code_byte(NOTOP); (luaY_val.vLong) = 0; }
#line 2032 "y.tab.c" /* yacc.c:1646  */
    break;

  case 36:
#line 589 "lua.y" /* yacc.c:1646  */
    { code_byte(LEOP);   (luaY_val.vLong) = 0; }
#line 2038 "y.tab.c" /* yacc.c:1646  */
    break;

  case 37:
#line 590 "lua.y" /* yacc.c:1646  */
    { code_byte(GEOP);   (luaY_val.vLong) = 0; }
#line 2044 "y.tab.c" /* yacc.c:1646  */
    break;

  case 38:
#line 591 "lua.y" /* yacc.c:1646  */
    { code_byte(ADDOP);  (luaY_val.vLong) = 0; }
#line 2050 "y.tab.c" /* yacc.c:1646  */
    break;

  case 39:
#line 592 "lua.y" /* yacc.c:1646  */
    { code_byte(SUBOP);  (luaY_val.vLong) = 0; }
#line 2056 "y.tab.c" /* yacc.c:1646  */
    break;

  case 40:
#line 593 "lua.y" /* yacc.c:1646  */
    { code_byte(MULTOP); (luaY_val.vLong) = 0; }
#line 2062 "y.tab.c" /* yacc.c:1646  */
    break;

  case 41:
#line 594 "lua.y" /* yacc.c:1646  */
    { code_byte(DIVOP);  (luaY_val.vLong) = 0; }
#line 2068 "y.tab.c" /* yacc.c:1646  */
    break;

  case 42:
#line 595 "lua.y" /* yacc.c:1646  */
    { code_byte(POWOP);  (luaY_val.vLong) = 0; }
#line 2074 "y.tab.c" /* yacc.c:1646  */
    break;

  case 43:
#line 596 "lua.y" /* yacc.c:1646  */
    { code_byte(CONCOP);  (luaY_val.vLong) = 0; }
#line 2080 "y.tab.c" /* yacc.c:1646  */
    break;

  case 44:
#line 597 "lua.y" /* yacc.c:1646  */
    { code_byte(MINUSOP); (luaY_val.vLong) = 0;}
#line 2086 "y.tab.c" /* yacc.c:1646  */
    break;

  case 45:
#line 598 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vLong) = 0; }
#line 2092 "y.tab.c" /* yacc.c:1646  */
    break;

  case 46:
#line 599 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vLong) = 0;}
#line 2098 "y.tab.c" /* yacc.c:1646  */
    break;

  case 47:
#line 600 "lua.y" /* yacc.c:1646  */
    { code_number((luaY_vsp[0].vFloat)); (luaY_val.vLong) = 0; }
#line 2104 "y.tab.c" /* yacc.c:1646  */
    break;

  case 48:
#line 602 "lua.y" /* yacc.c:1646  */
    {
       code_string((luaY_vsp[0].vWord));
       (luaY_val.vLong) = 0;
     }
#line 2113 "y.tab.c" /* yacc.c:1646  */
    break;

  case 49:
#line 606 "lua.y" /* yacc.c:1646  */
    {code_byte(PUSHNIL); (luaY_val.vLong) = 0; }
#line 2119 "y.tab.c" /* yacc.c:1646  */
    break;

  case 50:
#line 607 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vLong) = (luaY_vsp[0].vLong); }
#line 2125 "y.tab.c" /* yacc.c:1646  */
    break;

  case 51:
#line 608 "lua.y" /* yacc.c:1646  */
    { code_byte(NOTOP);  (luaY_val.vLong) = 0;}
#line 2131 "y.tab.c" /* yacc.c:1646  */
    break;

  case 52:
#line 609 "lua.y" /* yacc.c:1646  */
    {code_byte(POP); }
#line 2137 "y.tab.c" /* yacc.c:1646  */
    break;

  case 53:
#line 610 "lua.y" /* yacc.c:1646  */
    { 
      basepc[(luaY_vsp[-2].vLong)] = ONFJMP;
      code_word_at(basepc+(luaY_vsp[-2].vLong)+1, pc - ((luaY_vsp[-2].vLong) + sizeof(Word)+1));
      (luaY_val.vLong) = 0;
     }
#line 2147 "y.tab.c" /* yacc.c:1646  */
    break;

  case 54:
#line 615 "lua.y" /* yacc.c:1646  */
    {code_byte(POP); }
#line 2153 "y.tab.c" /* yacc.c:1646  */
    break;

  case 55:
#line 616 "lua.y" /* yacc.c:1646  */
    { 
      basepc[(luaY_vsp[-2].vLong)] = ONTJMP;
      code_word_at(basepc+(luaY_vsp[-2].vLong)+1, pc - ((luaY_vsp[-2].vLong) + sizeof(Word)+1));
      (luaY_val.vLong) = 0;
     }
#line 2163 "y.tab.c" /* yacc.c:1646  */
    break;

  case 56:
#line 624 "lua.y" /* yacc.c:1646  */
    {
      code_byte(CREATEARRAY);
      (luaY_val.vLong) = pc; code_word(0);
     }
#line 2172 "y.tab.c" /* yacc.c:1646  */
    break;

  case 57:
#line 629 "lua.y" /* yacc.c:1646  */
    {
      code_word_at(basepc+(luaY_vsp[-3].vLong), (luaY_vsp[-1].vInt));
     }
#line 2180 "y.tab.c" /* yacc.c:1646  */
    break;

  case 58:
#line 635 "lua.y" /* yacc.c:1646  */
    {
	  code_byte(CALLFUNC);
	  code_byte((luaY_vsp[-1].vInt)+(luaY_vsp[0].vInt));
	  (luaY_val.vLong) = pc;
	  code_byte(0);  /* may be modified by other rules */
	}
#line 2191 "y.tab.c" /* yacc.c:1646  */
    break;

  case 59:
#line 643 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = 0; }
#line 2197 "y.tab.c" /* yacc.c:1646  */
    break;

  case 60:
#line 645 "lua.y" /* yacc.c:1646  */
    { 
               code_byte(PUSHSELF); 
	       code_word(luaI_findconstant((luaY_vsp[0].pTStr)));
               (luaY_val.vInt) = 1;
	     }
#line 2207 "y.tab.c" /* yacc.c:1646  */
    break;

  case 61:
#line 653 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = adjust_functioncall((luaY_vsp[-1].vLong), 1); }
#line 2213 "y.tab.c" /* yacc.c:1646  */
    break;

  case 62:
#line 654 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = 1; }
#line 2219 "y.tab.c" /* yacc.c:1646  */
    break;

  case 63:
#line 657 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vLong) = 0; }
#line 2225 "y.tab.c" /* yacc.c:1646  */
    break;

  case 64:
#line 658 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vLong) = (luaY_vsp[0].vLong); }
#line 2231 "y.tab.c" /* yacc.c:1646  */
    break;

  case 65:
#line 661 "lua.y" /* yacc.c:1646  */
    { if ((luaY_vsp[0].vLong) != 0) (luaY_val.vLong) = (luaY_vsp[0].vLong); else (luaY_val.vLong) = -1; }
#line 2237 "y.tab.c" /* yacc.c:1646  */
    break;

  case 66:
#line 662 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vLong) = adjust_functioncall((luaY_vsp[-1].vLong), 1); }
#line 2243 "y.tab.c" /* yacc.c:1646  */
    break;

  case 67:
#line 663 "lua.y" /* yacc.c:1646  */
    {
	  if ((luaY_vsp[0].vLong) == 0) (luaY_val.vLong) = -((luaY_vsp[-1].vLong) + 1);  /* -length */
	  else
	  {
	    adjust_functioncall((luaY_vsp[0].vLong), (luaY_vsp[-1].vLong));
	    (luaY_val.vLong) = (luaY_vsp[0].vLong);
	  }
	}
#line 2256 "y.tab.c" /* yacc.c:1646  */
    break;

  case 68:
#line 673 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = close_parlist(0); }
#line 2262 "y.tab.c" /* yacc.c:1646  */
    break;

  case 69:
#line 674 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = close_parlist((luaY_vsp[0].vInt)); }
#line 2268 "y.tab.c" /* yacc.c:1646  */
    break;

  case 70:
#line 677 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = (luaY_vsp[0].vInt); }
#line 2274 "y.tab.c" /* yacc.c:1646  */
    break;

  case 71:
#line 679 "lua.y" /* yacc.c:1646  */
    {
	  if ((luaY_vsp[-2].vInt))
            lua_error("invalid parameter list");
          (luaY_val.vInt) = (luaY_vsp[0].vInt);
	}
#line 2284 "y.tab.c" /* yacc.c:1646  */
    break;

  case 72:
#line 686 "lua.y" /* yacc.c:1646  */
    { add_localvar((luaY_vsp[0].pTStr)); (luaY_val.vInt) = 0; }
#line 2290 "y.tab.c" /* yacc.c:1646  */
    break;

  case 73:
#line 687 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = 1; }
#line 2296 "y.tab.c" /* yacc.c:1646  */
    break;

  case 74:
#line 691 "lua.y" /* yacc.c:1646  */
    { flush_list((luaY_vsp[0].vInt)/FIELDS_PER_FLUSH, (luaY_vsp[0].vInt)%FIELDS_PER_FLUSH); }
#line 2302 "y.tab.c" /* yacc.c:1646  */
    break;

  case 75:
#line 693 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = (luaY_vsp[-2].vInt)+(luaY_vsp[0].vInt); }
#line 2308 "y.tab.c" /* yacc.c:1646  */
    break;

  case 76:
#line 695 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = (luaY_vsp[-1].vInt); flush_record((luaY_vsp[-1].vInt)%FIELDS_PER_FLUSH); }
#line 2314 "y.tab.c" /* yacc.c:1646  */
    break;

  case 77:
#line 699 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = 0; }
#line 2320 "y.tab.c" /* yacc.c:1646  */
    break;

  case 78:
#line 701 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = (luaY_vsp[0].vInt); flush_record((luaY_vsp[0].vInt)%FIELDS_PER_FLUSH); }
#line 2326 "y.tab.c" /* yacc.c:1646  */
    break;

  case 81:
#line 708 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = 0; }
#line 2332 "y.tab.c" /* yacc.c:1646  */
    break;

  case 82:
#line 709 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = (luaY_vsp[-1].vInt); }
#line 2338 "y.tab.c" /* yacc.c:1646  */
    break;

  case 83:
#line 712 "lua.y" /* yacc.c:1646  */
    {(luaY_val.vInt)=1;}
#line 2344 "y.tab.c" /* yacc.c:1646  */
    break;

  case 84:
#line 714 "lua.y" /* yacc.c:1646  */
    {
		  (luaY_val.vInt)=(luaY_vsp[-2].vInt)+1;
		  if ((luaY_val.vInt)%FIELDS_PER_FLUSH == 0) flush_record(FIELDS_PER_FLUSH);
		}
#line 2353 "y.tab.c" /* yacc.c:1646  */
    break;

  case 87:
#line 724 "lua.y" /* yacc.c:1646  */
    { code_constant((luaY_vsp[0].pTStr)); }
#line 2359 "y.tab.c" /* yacc.c:1646  */
    break;

  case 88:
#line 727 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = 0; }
#line 2365 "y.tab.c" /* yacc.c:1646  */
    break;

  case 89:
#line 728 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = (luaY_vsp[-1].vInt); }
#line 2371 "y.tab.c" /* yacc.c:1646  */
    break;

  case 90:
#line 731 "lua.y" /* yacc.c:1646  */
    {(luaY_val.vInt)=1;}
#line 2377 "y.tab.c" /* yacc.c:1646  */
    break;

  case 91:
#line 733 "lua.y" /* yacc.c:1646  */
    {
		  (luaY_val.vInt)=(luaY_vsp[-2].vInt)+1;
		  if ((luaY_val.vInt)%FIELDS_PER_FLUSH == 0) 
		    flush_list((luaY_val.vInt)/FIELDS_PER_FLUSH - 1, FIELDS_PER_FLUSH);
		}
#line 2387 "y.tab.c" /* yacc.c:1646  */
    break;

  case 92:
#line 741 "lua.y" /* yacc.c:1646  */
    {
	   nvarbuffer = 0; 
	   add_varbuffer((luaY_vsp[0].vLong));
	   (luaY_val.vInt) = ((luaY_vsp[0].vLong) == 0) ? 1 : 0;
	  }
#line 2397 "y.tab.c" /* yacc.c:1646  */
    break;

  case 93:
#line 747 "lua.y" /* yacc.c:1646  */
    { 
	   add_varbuffer((luaY_vsp[0].vLong));
	   (luaY_val.vInt) = ((luaY_vsp[0].vLong) == 0) ? (luaY_vsp[-2].vInt) + 1 : (luaY_vsp[-2].vInt);
	  }
#line 2406 "y.tab.c" /* yacc.c:1646  */
    break;

  case 94:
#line 753 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vLong) = (luaY_vsp[0].vLong); }
#line 2412 "y.tab.c" /* yacc.c:1646  */
    break;

  case 95:
#line 755 "lua.y" /* yacc.c:1646  */
    {
	   (luaY_val.vLong) = 0;		/* indexed variable */
	  }
#line 2420 "y.tab.c" /* yacc.c:1646  */
    break;

  case 96:
#line 759 "lua.y" /* yacc.c:1646  */
    {
	    code_constant((luaY_vsp[0].pTStr));
	    (luaY_val.vLong) = 0;		/* indexed variable */
	  }
#line 2429 "y.tab.c" /* yacc.c:1646  */
    break;

  case 97:
#line 766 "lua.y" /* yacc.c:1646  */
    {
	   int local = lua_localname((luaY_vsp[0].pTStr));
	   if (local == -1)	/* global var */
	    (luaY_val.vLong) = luaI_findsymbol((luaY_vsp[0].pTStr))+1;  /* return positive value */
           else
	    (luaY_val.vLong) = -(local+1);		/* return negative value */
	  }
#line 2441 "y.tab.c" /* yacc.c:1646  */
    break;

  case 98:
#line 775 "lua.y" /* yacc.c:1646  */
    { lua_pushvar((luaY_vsp[0].vLong)); }
#line 2447 "y.tab.c" /* yacc.c:1646  */
    break;

  case 99:
#line 778 "lua.y" /* yacc.c:1646  */
    {store_localvar((luaY_vsp[0].pTStr), 0); (luaY_val.vInt) = 1;}
#line 2453 "y.tab.c" /* yacc.c:1646  */
    break;

  case 100:
#line 780 "lua.y" /* yacc.c:1646  */
    {
	     store_localvar((luaY_vsp[0].pTStr), (luaY_vsp[-2].vInt));
	     (luaY_val.vInt) = (luaY_vsp[-2].vInt)+1;
	    }
#line 2462 "y.tab.c" /* yacc.c:1646  */
    break;

  case 101:
#line 786 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = 0; }
#line 2468 "y.tab.c" /* yacc.c:1646  */
    break;

  case 102:
#line 787 "lua.y" /* yacc.c:1646  */
    { (luaY_val.vInt) = (luaY_vsp[0].vLong); }
#line 2474 "y.tab.c" /* yacc.c:1646  */
    break;


#line 2478 "y.tab.c" /* yacc.c:1646  */
      default: break;
    }
  /* User semantic actions sometimes alter luaY_char, and that requires
     that luaY_token be updated with the new translation.  We take the
     approach of translating immediately before every use of luaY_token.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering luaY_char or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", luaY_r1[luaY_n], &luaY_val, &luaY_loc);

  YYPOPSTACK (luaY_len);
  luaY_len = 0;
  YY_STACK_PRINT (luaY_ss, luaY_ssp);

  *++luaY_vsp = luaY_val;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */

  luaY_n = luaY_r1[luaY_n];

  luaY_state = luaY_pgoto[luaY_n - YYNTOKENS] + *luaY_ssp;
  if (0 <= luaY_state && luaY_state <= YYLAST && luaY_check[luaY_state] == *luaY_ssp)
    luaY_state = luaY_table[luaY_state];
  else
    luaY_state = luaY_defgoto[luaY_n - YYNTOKENS];

  goto luaY_newstate;


/*--------------------------------------.
| luaY_errlab -- here on detecting error.  |
`--------------------------------------*/
luaY_errlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  luaY_token = luaY_char == YYEMPTY ? YYEMPTY : YYTRANSLATE (luaY_char);

  /* If not already recovering from an error, report this error.  */
  if (!luaY_errstatus)
    {
      ++luaY_nerrs;
#if ! YYERROR_VERBOSE
      luaY_error (YY_("syntax error"));
#else
# define YYSYNTAX_ERROR luaY_syntax_error (&luaY_msg_alloc, &luaY_msg, \
                                        luaY_ssp, luaY_token)
      {
        char const *luaY_msgp = YY_("syntax error");
        int luaY_syntax_error_status;
        luaY_syntax_error_status = YYSYNTAX_ERROR;
        if (luaY_syntax_error_status == 0)
          luaY_msgp = luaY_msg;
        else if (luaY_syntax_error_status == 1)
          {
            if (luaY_msg != luaY_msgbuf)
              YYSTACK_FREE (luaY_msg);
            luaY_msg = (char *) YYSTACK_ALLOC (luaY_msg_alloc);
            if (!luaY_msg)
              {
                luaY_msg = luaY_msgbuf;
                luaY_msg_alloc = sizeof luaY_msgbuf;
                luaY_syntax_error_status = 2;
              }
            else
              {
                luaY_syntax_error_status = YYSYNTAX_ERROR;
                luaY_msgp = luaY_msg;
              }
          }
        luaY_error (luaY_msgp);
        if (luaY_syntax_error_status == 2)
          goto luaY_exhaustedlab;
      }
# undef YYSYNTAX_ERROR
#endif
    }



  if (luaY_errstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (luaY_char <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (luaY_char == YYEOF)
            YYABORT;
        }
      else
        {
          luaY_destruct ("Error: discarding",
                      luaY_token, &luaY_lval);
          luaY_char = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto luaY_errlab1;


/*---------------------------------------------------.
| luaY_errorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
luaY_errorlab:

  /* Pacify compilers like GCC when the user code never invokes
     YYERROR and the label luaY_errorlab therefore never appears in user
     code.  */
  if (/*CONSTCOND*/ 0)
     goto luaY_errorlab;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (luaY_len);
  luaY_len = 0;
  YY_STACK_PRINT (luaY_ss, luaY_ssp);
  luaY_state = *luaY_ssp;
  goto luaY_errlab1;


/*-------------------------------------------------------------.
| luaY_errlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
luaY_errlab1:
  luaY_errstatus = 3;      /* Each real token shifted decrements this.  */

  for (;;)
    {
      luaY_n = luaY_pact[luaY_state];
      if (!luaY_pact_value_is_default (luaY_n))
        {
          luaY_n += YYTERROR;
          if (0 <= luaY_n && luaY_n <= YYLAST && luaY_check[luaY_n] == YYTERROR)
            {
              luaY_n = luaY_table[luaY_n];
              if (0 < luaY_n)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (luaY_ssp == luaY_ss)
        YYABORT;


      luaY_destruct ("Error: popping",
                  luaY_stos[luaY_state], luaY_vsp);
      YYPOPSTACK (1);
      luaY_state = *luaY_ssp;
      YY_STACK_PRINT (luaY_ss, luaY_ssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++luaY_vsp = luaY_lval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", luaY_stos[luaY_n], luaY_vsp, luaY_lsp);

  luaY_state = luaY_n;
  goto luaY_newstate;


/*-------------------------------------.
| luaY_acceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
luaY_acceptlab:
  luaY_result = 0;
  goto luaY_return;

/*-----------------------------------.
| luaY_abortlab -- YYABORT comes here.  |
`-----------------------------------*/
luaY_abortlab:
  luaY_result = 1;
  goto luaY_return;

#if !defined luaY_overflow || YYERROR_VERBOSE
/*-------------------------------------------------.
| luaY_exhaustedlab -- memory exhaustion comes here.  |
`-------------------------------------------------*/
luaY_exhaustedlab:
  luaY_error (YY_("memory exhausted"));
  luaY_result = 2;
  /* Fall through.  */
#endif

luaY_return:
  if (luaY_char != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      luaY_token = YYTRANSLATE (luaY_char);
      luaY_destruct ("Cleanup: discarding lookahead",
                  luaY_token, &luaY_lval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (luaY_len);
  YY_STACK_PRINT (luaY_ss, luaY_ssp);
  while (luaY_ssp != luaY_ss)
    {
      luaY_destruct ("Cleanup: popping",
                  luaY_stos[*luaY_ssp], luaY_vsp);
      YYPOPSTACK (1);
    }
#ifndef luaY_overflow
  if (luaY_ss != luaY_ssa)
    YYSTACK_FREE (luaY_ss);
#endif
#if YYERROR_VERBOSE
  if (luaY_msg != luaY_msgbuf)
    YYSTACK_FREE (luaY_msg);
#endif
  return luaY_result;
}
#line 790 "lua.y" /* yacc.c:1906  */

